### ISSUE TITLE
List of categories does not return categories

### ISSUE THREAD

**Issue by kumarRaj** [kumarRaj/stocks#31]
This endpoint `localhost:8081/stock/categories` does not return anything

**Comment by kumarRaj** [comment]
```stocks-backend    | Exception in reading file content : /root/stocks/data/categories (No such file or directory)
stocks-backend    | java.io.FileNotFoundException: /root/stocks/data/categories (No such file or directory)
stocks-backend    | 	at java.base/java.io.FileInputStream.open0(Native Method)
stocks-backend    | 	at java.base/java.io.FileInputStream.open(Unknown Source)
stocks-backend    | 	at java.base/java.io.FileInputStream.<init>(Unknown Source)
stocks-backend    | 	at java.base/java.util.Scanner.<init>(Unknown Source)
stocks-backend    | 	at com.project.stocks.service.File.readFile(File.java:13)
stocks-backend    | 	at com.project.stocks.repository.StockRepository.getStockDetails(StockRepository.java:17)
stocks-backend    | 	at com.project.stocks.service.StockService.getStockDetails(StockService.java:24)
stocks-backend    | 	at com.project.stocks.controller.StocksController.getStockDetails(StocksController.java:24)
stocks-backend    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
stocks-backend    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
stocks-backend    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
stocks-backend    | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)```

**Comment by SunandanBose** [comment]
Unable to replicate it. Please restart server and try on Incognito

**Comment by kumarRaj** [comment]
Fixed. removed trailing slash in this commit 133d1833f15d10ee7d4a8ce6dcbe2d9a491d37b5
